### ISSUE TITLE
the driver can't be compiled with kernel 6.15 (fix mentioned)

### ISSUE THREAD

**Issue by vorasilp** [shenmintao/aic8800d80#7]
There are errors when compile with kernel 6.15. The cause is that functions `del_timer() ` and `del_timer_sync()` were removed from kernel since 6.15. They are meant to be replaced by `timer_delete()` and `timer_delete_sync()`. 

Here is one of the compile errors,

> aic8800_fdrv/rwnx_main.c:2443:25: error: implicit declaration of function ‘del_timer_sync’; did you mean ‘dev_mc_sync’? [-Wimplicit-function-declaration]
>  2443 |                         del_timer_sync(&rwnx_hw->p2p_alive_timer);
>       |                         ^~~~~~~~~~~~~~
>       |                         dev_mc_sync

After rename all `del_timer()` and `del_timer_sync()`, the driver can be compiled without error. I tested it with Opensuse tumbleweed kernel 6.15 (x64) , Opensuse tumbleweed kernel 6.14 (arm64) and Raspberry Pi OS kernel  6.12 (arm64).

Here the diff:
[kernel-6.15.diff.txt](https://github.com/user-attachments/files/20608434/kernel-6.15.diff.txt)

I can do a pull request if you'd like.

**Comment by shenmintao** [comment]
Thank you so much for identifying the issue, creating the patch, and testing it across different kernels! I really appreciate you taking the time to do that.

My apologies for the slow reply; things have been a bit busy for me recently. I would be very happy to review and merge a pull request from you. Please feel free to submit it whenever you're ready.

Thanks again for your contribution!
@vorasilp

**Comment by vorasilp** [comment]
my PR sent 🙂
