### PR TITLE
fix: select cfg80211 callbacks by declared type

### PR DESCRIPTION
**Pull request by lucaskawatoko**
Distributions and OpenWrt backport individual `cfg80211` API changes into stable series without moving `LINUX_VERSION_CODE`. A numeric version test therefore picks the wrong prototype and the build fails with `-Wincompatible-pointer-types`. Debian 13 (`6.12.107`) is one such kernel for `set_monitor_channel()`, which gained a `struct net_device *dev` argument in mainline 6.13 and in the 6.12 stable series from 6.12.101.

This change stops guessing from the version number and asks the compiler which prototype the headers actually declare.

## What it adds

- `AICWF_CFG80211_OP_FIELD()` reads the real type of a `cfg80211_ops` member
- `AICWF_CFG80211_OP_IS()` tests it against a callback shape
- `AICWF_CFG80211_OP_REQUIRE()` turns that test into a compile-time assertion
- `AICWF_CFG80211_HELPER_IS()` / `_REQUIRE()` do the same for free `cfg80211` helpers

`set_monitor_channel()` now has a shared body and two thin wrappers. The ops table selects the wrapper matching the headers through `__builtin_choose_expr`, so no `#if` on the version is needed at the call sites.

## Assertions as early warning

The callbacks that have changed shape before but are not reshaped here yet (`set_wiphy_params`, `start_radar_detection`, `set_tx_power`, `get_tx_power`, and the `cfg80211_cac_event` helper) get assertions only. They do not select a variant. They turn a future silent incompatibility into an explicit diagnostic naming the callback to fix:

```
error: size of array 'aicwf_cfg80211_set_wiphy_params_shape_must_be_supported' is negative
```

## Verification

Built on five kernels, each producing `aic8800_fdrv.ko` with 0 errors and 0 new warnings:

| Kernel | Result |
|---|---|
| 5.15.0-191-generic | ok |
| 6.1.0-53-amd64 | ok |
| 6.8.0-139-generic | ok |
| 6.11.0-8-generic | ok |
| 6.12.107+deb13-amd64 | ok |

The 6.12 build was inspected to confirm the ops table references the three-argument wrapper (`rwnx_cfg80211_set_monitor_channel_three`), and negative tests confirm each assertion fails with the expected array-size error when a shape is deliberately changed.

## Relation to #97

#97 fixed the same `set_monitor_channel` break with a version threshold (`>= 6.12.101`). It solves today's case but breaks again if a backport lands without a version bump, or if a future kernel reshapes the callback. This PR keeps the same fix and makes it survive that. #97 can be closed in favour of this one, or kept as the minimal change if you prefer; both are mergeable on their own.

### CODE REVIEW

**Comment by shenmintao** [comment]
Thanks for the extra work on this. I merged #97 as the fix for #96 and am closing this one, because the additional compile-time assertions break the build on current kernels.

Building `f796ab3` against the same headers as #97:

| Headers | Result |
| --- | --- |
| Debian 13 `6.12.107+deb13-amd64` | pass |
| Ubuntu `6.8.0-139` | pass |
| Ubuntu `6.11.0-17` | pass |
| Ubuntu `6.14.0-27` | **fails** |
| Ubuntu `6.17.0-14` | **fails** |

```
6.14: rwnx_compat.h:62:18: error: size of array 'aicwf_cfg80211_get_tx_power_shape_must_be_supported' is negative
6.17: rwnx_compat.h:62:18: error: size of array 'aicwf_cfg80211_set_tx_power_shape_must_be_supported' is negative
      rwnx_compat.h:62:18: error: size of array 'aicwf_cfg80211_get_tx_power_shape_must_be_supported' is negative
```

The accepted shapes do not match the real prototypes:

- `get_tx_power()` gained `unsigned int link_id` in 6.14: `(wiphy, wdev, link_id, dbm)`. From 6.17 it is `(wiphy, wdev, int radio_idx, unsigned int link_id, int *dbm)`.
- `set_tx_power()` in 6.17 is `(wiphy, wdev, int radio_idx, type, mbm)`, with `radio_idx` after `wdev`, not before it.

The v6.18.53 and v7.2.7 stable headers have the same shapes, so every kernel from 6.14 onward would fail to build. The driver's own callbacks already use the correct order, which is why `main` builds there.

Beyond the prototypes, I would rather not add assertions for callbacks the driver does not select through this mechanism: the ops-table initializer already fails with `-Wincompatible-pointer-types` when a prototype changes, and every assertion is one more table that has to be kept exactly in sync with upstream. If a backport without a version bump shows up for another callback, a targeted type-based selection for that callback would be welcome as a separate PR.

**Comment by lucaskawatoko** [comment]
Fair catch — the `radio_idx` order and the 6.14 `link_id` were wrong, and an assertion that breaks the build on 6.14+ is worse than no assertion. Thanks for digging into it instead of just closing, and for merging #97. I'll keep an eye on the backports; if a real gap shows up for a specific callback, I'll come back with the type-based selection focused just on it.
