### ISSUE TITLE
DKMS build failed: make exit code: 2

### ISSUE THREAD

**Issue by jkroepke** [shenmintao/aic8800d80#82]
I'm trying to install this on my RPI, but I get an error:

```

╔════════════════════════════════════════════════════════════════╗
║     AIC8800D80 WiFi 6 Driver - Universal Installer (DKMS)      ║
║                   Version 2.0.4 (Fixed)                        ║
╚════════════════════════════════════════════════════════════════╝


==> Checking Secure Boot status...
[SUCCESS] Secure Boot is disabled or not present.

==> Detecting package manager and distribution...
[SUCCESS] Detected: Debian/Ubuntu (apt)

==> Installing dependencies...
[INFO] Kernel build tree already exists; skipping generic kernel headers package.
[INFO] Updating package database...
Hit:1 http://raspbian.raspberrypi.com/raspbian trixie InRelease
Hit:2 http://archive.raspberrypi.com/debian trixie InRelease
Reading package lists...
[INFO] Installing: dkms build-essential mokutil eject usb-modeswitch...
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version (3.2.2-1~deb13u1).
build-essential is already the newest version (12.12).
mokutil is already the newest version (0.7.2-1).
eject is already the newest version (2.41-5).
usb-modeswitch is already the newest version (2.6.1-4+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[SUCCESS] Dependencies installed successfully.

==> Installing firmware...
[INFO] Removing existing firmware...
[INFO] Installing firmware for all chip variants...
[INFO] Copying aic8800 firmware to /lib/firmware/aic8800...
[INFO] Copying aic8800D80 firmware to /lib/firmware/aic8800D80...
[INFO] Copying aic8800D80N firmware to /lib/firmware/aic8800D80N...
[INFO] Copying aic8800D80X2 firmware to /lib/firmware/aic8800D80X2...
[INFO] Copying aic8800DC firmware to /lib/firmware/aic8800DC...
[INFO] Copying aic8800DLN firmware to /lib/firmware/aic8800DLN...
[SUCCESS] Firmware installed for all supported chip variants.
[INFO] Installing udev rules to /usr/lib/udev/rules.d/aic.rules...
[SUCCESS] Udev rules installed successfully.
[INFO] Installing usb_modeswitch configuration to /etc/usb_modeswitch.d/1111:1111...
[SUCCESS] USB modeswitch configuration installed successfully.
[SUCCESS] Firmware installed successfully.

==> Configuring DKMS...
[INFO] DKMS configuration file already exists.

==> Installing driver via DKMS...
[INFO] Removing existing DKMS installation...
[INFO] Cleaning up old source directory...
[INFO] Copying source files to /usr/src/aic8800-1.0.0...
[INFO] Adding module to DKMS...
[INFO] Building module (this may take a few minutes)...
[ERROR] DKMS build failed!

Please check the log file: /tmp/aic8800d80_install.log
Common issues:
  - Missing kernel headers
  - Compiler version mismatch
  - Kernel version too new/old
```

```
root@JOE-PI:~/aic8800d80# cat /tmp/aic8800d80_install.log
[2026-08-05 22:53:41] [START] Installation started
[2026-08-05 22:53:41] [INFO] Kernel: 6.18.39+rpt-rpi-v7
[2026-08-05 22:53:41] [INFO] Distribution: Raspbian GNU/Linux 13 (trixie)
[2026-08-05 22:53:41] [STEP] Checking Secure Boot status...
[2026-08-05 22:53:41] [SUCCESS] Secure Boot is disabled or not present.
[2026-08-05 22:53:41] [STEP] Detecting package manager and distribution...
[2026-08-05 22:53:41] [SUCCESS] Detected: Debian/Ubuntu (apt)
[2026-08-05 22:53:41] [STEP] Installing dependencies...
[2026-08-05 22:53:41] [INFO] Kernel build tree already exists; skipping generic kernel headers package.
[2026-08-05 22:53:41] [INFO] Updating package database...
Hit:1 http://raspbian.raspberrypi.com/raspbian trixie InRelease
Hit:2 http://archive.raspberrypi.com/debian trixie InRelease
Reading package lists...
[2026-08-05 22:53:54] [INFO] Installing: dkms build-essential mokutil eject usb-modeswitch...
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version (3.2.2-1~deb13u1).
build-essential is already the newest version (12.12).
mokutil is already the newest version (0.7.2-1).
eject is already the newest version (2.41-5).
usb-modeswitch is already the newest version (2.6.1-4+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[2026-08-05 22:54:04] [SUCCESS] Dependencies installed successfully.
[2026-08-05 22:54:04] [STEP] Installing firmware...
[2026-08-05 22:54:05] [INFO] Removing existing firmware...
[2026-08-05 22:54:05] [INFO] Installing firmware for all chip variants...
[2026-08-05 22:54:05] [INFO] Copying aic8800 firmware to /lib/firmware/aic8800...
[2026-08-05 22:54:05] [INFO] Copying aic8800D80 firmware to /lib/firmware/aic8800D80...
[2026-08-05 22:54:06] [INFO] Copying aic8800D80N firmware to /lib/firmware/aic8800D80N...
[2026-08-05 22:54:06] [INFO] Copying aic8800D80X2 firmware to /lib/firmware/aic8800D80X2...
[2026-08-05 22:54:06] [INFO] Copying aic8800DC firmware to /lib/firmware/aic8800DC...
[2026-08-05 22:54:06] [INFO] Copying aic8800DLN firmware to /lib/firmware/aic8800DLN...
[2026-08-05 22:54:06] [SUCCESS] Firmware installed for all supported chip variants.
[2026-08-05 22:54:06] [INFO] Installing udev rules to /usr/lib/udev/rules.d/aic.rules...
[2026-08-05 22:54:06] [SUCCESS] Udev rules installed successfully.
[2026-08-05 22:54:06] [INFO] Installing usb_modeswitch configuration to /etc/usb_modeswitch.d/1111:1111...
[2026-08-05 22:54:06] [SUCCESS] USB modeswitch configuration installed successfully.
[2026-08-05 22:54:07] [SUCCESS] Firmware installed successfully.
[2026-08-05 22:54:07] [STEP] Configuring DKMS...
[2026-08-05 22:54:07] [INFO] DKMS configuration file already exists.
[2026-08-05 22:54:07] [STEP] Installing driver via DKMS...
[2026-08-05 22:54:08] [INFO] Removing existing DKMS installation...
Deleting module aic8800/1.0.0 completely from the DKMS tree.
[2026-08-05 22:54:08] [INFO] Cleaning up old source directory...
[2026-08-05 22:54:08] [INFO] Copying source files to /usr/src/aic8800-1.0.0...
[2026-08-05 22:54:09] [INFO] Adding module to DKMS...
Creating symlink /var/lib/dkms/aic8800/1.0.0/source -> /usr/src/aic8800-1.0.0
[2026-08-05 22:54:10] [INFO] Building module (this may take a few minutes)...
The kernel is built without module signing facility, modules won't be signed

Building module(s)........................................................................(bad exit status: 2)
Failed command:
KVER=6.18.39+rpt-rpi-v7 KDIR=/lib/modules/6.18.39+rpt-rpi-v7/build 'make' -C drivers/aic8800

Error! Bad return status for module build on kernel: 6.18.39+rpt-rpi-v7 (armv7l)
Consult /var/lib/dkms/aic8800/1.0.0/build/make.log for more information.
[2026-08-05 22:57:45] [ERROR] DKMS build failed!
```

```
root@JOE-PI:~/aic8800d80# cat /var/lib/dkms/aic8800/1.0.0/build/make.log
DKMS (dkms-3.2.2) make.log for aic8800/1.0.0 for kernel 6.18.39+rpt-rpi-v7 (armv7l)
Wed Aug  5 10:54:14 PM CEST 2026

Building module(s)
# command: KVER=6.18.39+rpt-rpi-v7 KDIR=/lib/modules/6.18.39+rpt-rpi-v7/build 'make' -C drivers/aic8800
make: Entering directory '/var/lib/dkms/aic8800/1.0.0/build/drivers/aic8800'
make -C /lib/modules/6.18.39+rpt-rpi-v7/build M=/var/lib/dkms/aic8800/1.0.0/build/drivers/aic8800 ARCH=arm CROSS_COMPILE=  modules
make[1]: Entering directory '/usr/src/linux-headers-6.18.39+rpt-rpi-v7'
make[2]: Entering directory '/var/lib/dkms/aic8800/1.0.0/build/drivers/aic8800'
  CC [M]  aic_load_fw/aic_bluetooth_main.o
  CC [M]  aic_zlp_quirk/aic_zlp_quirk.o
  CC [M]  aic8800_fdrv/rwnx_wakelock.o
  CC [M]  aic_load_fw/aicbluetooth.o
aic_zlp_quirk/aic_zlp_quirk.c: In function ‘usb_submit_urb_pre_handler’:
aic_zlp_quirk/aic_zlp_quirk.c:152:29: error: implicit declaration of function ‘regs_get_kernel_argument’; did you mean ‘regs_get_kernel_stack_nth’? [-Wimplicit-function-declaration]
  152 |         urb = (struct urb *)regs_get_kernel_argument(regs, 0);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
      |                             regs_get_kernel_stack_nth
make[5]: *** [/usr/src/linux-headers-6.18.39+rpt-common-rpi/scripts/Makefile.build:292: aic_zlp_quirk/aic_zlp_quirk.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.18.39+rpt-common-rpi/scripts/Makefile.build:549: aic_zlp_quirk] Error 2
make[4]: *** Waiting for unfinished jobs....
  CC [M]  aic_load_fw/aicwf_usb.o
  CC [M]  aic8800_fdrv/rwnx_msg_tx.o
  CC [M]  aic_load_fw/aic_txrxif.o
  CC [M]  aic8800_fdrv/rwnx_msg_rx.o
  CC [M]  aic_load_fw/aicbluetooth_cmds.o
aic8800_fdrv/rwnx_msg_tx.c: In function ‘rwnx_send_add_if’:
aic8800_fdrv/rwnx_msg_tx.c:620:31: warning: this statement may fall through [-Wimplicit-fallthrough=]
  620 |         add_if_req_param->p2p = true;
      |         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
aic8800_fdrv/rwnx_msg_tx.c:623:5: note: here
  623 |     case NL80211_IFTYPE_STATION:
      |     ^~~~
aic8800_fdrv/rwnx_msg_tx.c:633:31: warning: this statement may fall through [-Wimplicit-fallthrough=]
  633 |         add_if_req_param->p2p = true;
      |         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
aic8800_fdrv/rwnx_msg_tx.c:636:5: note: here
  636 |     case NL80211_IFTYPE_AP:
      |     ^~~~
  CC [M]  aic8800_fdrv/rwnx_utils.o
aic8800_fdrv/rwnx_msg_rx.c: In function ‘rwnx_rx_scanu_result_ind’:
aic8800_fdrv/rwnx_msg_rx.c:828:1: warning: label ‘putbss’ defined but not used [-Wunused-label]
  828 | putbss:
      | ^~~~~~
  CC [M]  aic_load_fw/aic_compat_8800d80.o
  CC [M]  aic8800_fdrv/rwnx_cmds.o
  CC [M]  aic_load_fw/aic_compat_8800d80x2.o
  CC [M]  aic8800_fdrv/rwnx_irqs.o
  CC [M]  aic_load_fw/md5.o
  CC [M]  aic8800_fdrv/rwnx_cfgfile.o
  CC [M]  aic_load_fw/aicwf_rx_prealloc.o
  CC [M]  aic_load_fw/aicwf_txq_prealloc.o
  CC [M]  aic8800_fdrv/rwnx_strs.o
  CC [M]  aic8800_fdrv/rwnx_rx.o
  CC [M]  aic8800_fdrv/rwnx_tx.o
  CC [M]  aic8800_fdrv/rwnx_txq.o
  LD [M]  aic_load_fw/aic_load_fw.o
  CC [M]  aic8800_fdrv/rwnx_main.o
aic8800_fdrv/rwnx_tx.c: In function ‘rwnx_select_txq’:
aic8800_fdrv/rwnx_tx.c:331:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
  331 |         rwnx_vif = rwnx_vif->ap_vlan.master;
      |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
aic8800_fdrv/rwnx_tx.c:332:5: note: here
  332 |     case NL80211_IFTYPE_AP:
      |     ^~~~
  CC [M]  aic8800_fdrv/rwnx_mod_params.o
aic8800_fdrv/rwnx_txq.c: In function ‘rwnx_txq_vif_for_each_sta’:
aic8800_fdrv/rwnx_txq.c:640:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
  640 |         rwnx_vif = rwnx_vif->ap_vlan.master;
      |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
aic8800_fdrv/rwnx_txq.c:641:5: note: here
  641 |     case NL80211_IFTYPE_AP:
      |     ^~~~
aic8800_fdrv/rwnx_main.c: In function ‘rwnx_fill_station_info’:
aic8800_fdrv/rwnx_main.c:5926:43: warning: this statement may fall through [-Wimplicit-fallthrough=]
 5926 |                 sinfo->rxrate.he_ru_alloc = rx_vect1->he.ru_size;
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
aic8800_fdrv/rwnx_main.c:5927:9: note: here
 5927 |         case FORMATMOD_HE_SU:
      |         ^~~~
aic8800_fdrv/rwnx_main.c: In function ‘rwnx_cfg80211_mgmt_tx’:
aic8800_fdrv/rwnx_main.c:5089:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
 5089 |             rwnx_vif = rwnx_vif->ap_vlan.master;
      |             ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
aic8800_fdrv/rwnx_main.c:5090:9: note: here
 5090 |         case NL80211_IFTYPE_AP:
      |         ^~~~
aic8800_fdrv/rwnx_main.c: In function ‘rwnx_cfg80211_change_iface’:
aic8800_fdrv/rwnx_main.c:2681:28: warning: this statement may fall through [-Wimplicit-fallthrough=]
 2681 |         vif->ap.generation = 0;
      |         ~~~~~~~~~~~~~~~~~~~^~~
aic8800_fdrv/rwnx_main.c:2683:5: note: here
 2683 |     case NL80211_IFTYPE_AP:
      |     ^~~~
  CC [M]  aic8800_fdrv/rwnx_mesh.o
aic8800_fdrv/rwnx_main.c: In function ‘rwnx_interface_add’:
aic8800_fdrv/rwnx_main.c:1952:30: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1952 |         vif->ap.next_mesh_pm = NL80211_MESH_POWER_ACTIVE;
      |         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
aic8800_fdrv/rwnx_main.c:1954:5: note: here
 1954 |     case NL80211_IFTYPE_AP:
      |     ^~~~
  CC [M]  aic8800_fdrv/rwnx_platform.o
  CC [M]  aic8800_fdrv/rwnx_pci.o
  CC [M]  aic8800_fdrv/rwnx_dini.o
  CC [M]  aic8800_fdrv/rwnx_v7.o
  CC [M]  aic8800_fdrv/ipc_host.o
In function ‘rwnx_plat_patch_load’,
    inlined from ‘rwnx_platform_on’ at aic8800_fdrv/rwnx_platform.c:3822:11:
aic8800_fdrv/rwnx_platform.c:1841:9: warning: ‘sprintf’ argument 3 overlaps destination object ‘aic_fw_path’ [-Wrestrict]
 1841 |         sprintf(aic_fw_path, "%s/%s", aic_fw_path, "aic8800DLN");
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aic8800_fdrv/rwnx_platform.c: In function ‘rwnx_platform_on’:
aic8800_fdrv/rwnx_platform.c:53:13: note: destination object referenced by ‘restrict’-qualified argument 1 was declared here
   53 | extern char aic_fw_path[FW_PATH_MAX_LEN];
      |             ^~~~~~~~~~~
In function ‘rwnx_plat_patch_load’,
    inlined from ‘rwnx_platform_on’ at aic8800_fdrv/rwnx_platform.c:3822:11:
aic8800_fdrv/rwnx_platform.c:1811:9: warning: ‘sprintf’ argument 3 overlaps destination object ‘aic_fw_path’ [-Wrestrict]
 1811 |         sprintf(aic_fw_path, "%s/%s", aic_fw_path, "aic8800D80N");
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aic8800_fdrv/rwnx_platform.c: In function ‘rwnx_platform_on’:
aic8800_fdrv/rwnx_platform.c:53:13: note: destination object referenced by ‘restrict’-qualified argument 1 was declared here
   53 | extern char aic_fw_path[FW_PATH_MAX_LEN];
      |             ^~~~~~~~~~~
In function ‘rwnx_plat_patch_load’,
    inlined from ‘rwnx_platform_on’ at aic8800_fdrv/rwnx_platform.c:3822:11:
aic8800_fdrv/rwnx_platform.c:1672:9: warning: ‘sprintf’ argument 3 overlaps destination object ‘aic_fw_path’ [-Wrestrict]
 1672 |         sprintf(aic_fw_path, "%s/%s", aic_fw_path, "aic8800DC");
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aic8800_fdrv/rwnx_platform.c: In function ‘rwnx_platform_on’:
aic8800_fdrv/rwnx_platform.c:53:13: note: destination object referenced by ‘restrict’-qualified argument 1 was declared here
   53 | extern char aic_fw_path[FW_PATH_MAX_LEN];
      |             ^~~~~~~~~~~
  CC [M]  aic8800_fdrv/rwnx_tdls.o
  CC [M]  aic8800_fdrv/regdb.o
  CC [M]  aic8800_fdrv/md5.o
  CC [M]  aic8800_fdrv/aic_vendor.o
  CC [M]  aic8800_fdrv/aic_priv_cmd.o
  CC [M]  aic8800_fdrv/aicwf_compat_8800dc.o
In file included from /usr/src/linux-headers-6.18.39+rpt-common-rpi/include/linux/array_size.h:5,
                 from /usr/src/linux-headers-6.18.39+rpt-common-rpi/include/linux/kernel.h:16,
                 from /usr/src/linux-headers-6.18.39+rpt-common-rpi/include/linux/interrupt.h:6,
                 from aic8800_fdrv/rwnx_defs.h:16,
                 from aic8800_fdrv/rwnx_tdls.h:16,
                 from aic8800_fdrv/rwnx_tdls.c:16:
aic8800_fdrv/rwnx_tdls.c: In function ‘rwnx_ac_from_wmm’:
/usr/src/linux-headers-6.18.39+rpt-common-rpi/include/linux/compiler.h:77:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
   77 | # define unlikely(x)    __builtin_expect(!!(x), 0)
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-6.18.39+rpt-common-rpi/include/linux/once_lite.h:33:17: note: in expansion of macro ‘unlikely’
   33 |                 unlikely(__ret_do_once);                                \
      |                 ^~~~~~~~
/usr/src/linux-headers-6.18.39+rpt-common-rpi/include/asm-generic/bug.h:148:9: note: in expansion of macro ‘DO_ONCE_LITE_IF’
  148 |         DO_ONCE_LITE_IF(condition, WARN_ON, 1)
      |         ^~~~~~~~~~~~~~~
aic8800_fdrv/rwnx_tdls.c:274:17: note: in expansion of macro ‘WARN_ON_ONCE’
  274 |                 WARN_ON_ONCE(1);
      |                 ^~~~~~~~~~~~
aic8800_fdrv/rwnx_tdls.c:275:9: note: here
  275 |         case 0:
      |         ^~~~
  CC [M]  aic8800_fdrv/aicwf_compat_8800d80.o
  CC [M]  aic8800_fdrv/aicwf_compat_8800d80x2.o
aic8800_fdrv/aicwf_compat_8800d80.c: In function ‘rwnx_plat_userconfig_load_8800d80’:
aic8800_fdrv/aicwf_compat_8800d80.c:43:13: warning: ‘sprintf’ argument 3 overlaps destination object ‘aic_fw_path’ [-Wrestrict]
   43 |             sprintf(aic_fw_path, "%s/%s", aic_fw_path, "aic8800D80");
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aic8800_fdrv/aicwf_compat_8800d80.c:9:13: note: destination object referenced by ‘restrict’-qualified argument 1 was declared here
    9 | extern char aic_fw_path[200];
      |             ^~~~~~~~~~~
  CC [M]  aic8800_fdrv/aicwf_compat_8800d80n.o
  CC [M]  aic8800_fdrv/aicwf_compat_8800dln.o
  CC [M]  aic8800_fdrv/rwnx_radar.o
aic8800_fdrv/aicwf_compat_8800d80x2.c: In function ‘rwnx_plat_userconfig_load_8800d80x2’:
aic8800_fdrv/aicwf_compat_8800d80x2.c:44:5: warning: ‘sprintf’ argument 3 overlaps destination object ‘aic_fw_path’ [-Wrestrict]
   44 |     sprintf(aic_fw_path, "%s/%s", aic_fw_path, "aic8800D80X2");
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aic8800_fdrv/aicwf_compat_8800d80x2.c:9:13: note: destination object referenced by ‘restrict’-qualified argument 1 was declared here
    9 | extern char aic_fw_path[200];
      |             ^~~~~~~~~~~
  CC [M]  aic8800_fdrv/rwnx_debugfs.o
  CC [M]  aic8800_fdrv/rwnx_fw_trace.o
  CC [M]  aic8800_fdrv/aicwf_tcp_ack.o
  CC [M]  aic8800_fdrv/usb_host.o
  CC [M]  aic8800_fdrv/aicwf_txrxif.o
  CC [M]  aic8800_fdrv/aicwf_usb.o
  LD [M]  aic8800_fdrv/aic8800_fdrv.o
make[3]: *** [/usr/src/linux-headers-6.18.39+rpt-common-rpi/Makefile:2069: .] Error 2
make[2]: *** [/usr/src/linux-headers-6.18.39+rpt-common-rpi/Makefile:260: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/aic8800/1.0.0/build/drivers/aic8800'
make[1]: *** [/usr/src/linux-headers-6.18.39+rpt-common-rpi/Makefile:260: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.18.39+rpt-rpi-v7'
make: *** [Makefile:80: modules] Error 2
make: Leaving directory '/var/lib/dkms/aic8800/1.0.0/build/drivers/aic8800'

# exit code: 2
# elapsed time: 00:03:31
----------------------------------------------------------------
```

```
root@JOE-PI:~/aic8800d80# git remote -v
origin	https://github.com/shenmintao/aic8800d80.git (fetch)
origin	https://github.com/shenmintao/aic8800d80.git (push)
```

**Comment by jkroepke** [comment]
An AI generated summary and fix. I can confirm, after apply the patch, the DKMS module is present and the interface is up.

```
I believe this is an ARM32 compatibility issue in `aic_zlp_quirk`, rather than a general DKMS or kernel-header problem.

The build runs on a 32-bit ARM kernel:

```text
DKMS make.log for aic8800/1.0.0 for kernel 6.18.39+rpt-rpi-v7 (armv7l)
```

It fails while compiling `aic_zlp_quirk.c`:

```text
aic_zlp_quirk/aic_zlp_quirk.c:152:29: error:
implicit declaration of function ‘regs_get_kernel_argument’
```

The problematic line is:

```c
urb = (struct urb *)regs_get_kernel_argument(regs, 0);
```

`regs_get_kernel_argument()` is not available on 32-bit ARM. On ARM32, the first function argument is stored in `regs->ARM_r0`.

A possible architecture-specific fix would be:

```c
#if defined(CONFIG_ARM)
    urb = (struct urb *)regs->ARM_r0;
#else
    urb = (struct urb *)regs_get_kernel_argument(regs, 0);
#endif
```

After applying this patch, the DKMS build can be retried with:

```bash
sudo dkms build -m aic8800 -v 1.0.0
```

or by running the installer again:

```bash
sudo ./install.sh
```

The other messages in the build log, such as the implicit fall-through and overlapping `sprintf()` warnings, do not appear to be responsible for the build failure. The fatal error is the missing `regs_get_kernel_argument()` implementation for ARM32.

I have not yet verified whether the patched module builds and works successfully on the Raspberry Pi, but this patch addresses the exact compiler error.
```

**Comment by shenmintao** [comment]
Fixed on main in commit 40f00e6. On 32-bit ARM, the kprobe handler now reads the first argument from ARM_r0; other architectures keep using regs_get_kernel_argument(). Thanks for confirming the patch on Raspberry Pi kernel 6.18.39+rpt-rpi-v7. The unchanged x86_64 path was also compile-tested against Linux 6.17 headers.

**Comment by shenmintao** [comment]
The fix has also been backported to the maintained legacy-mcu1 branch in commit fffad12.
